### ISSUE TITLE
Open and closes a tab for a split second when opening spotube...

### ISSUE THREAD

**Issue by TristanDelcourt** [dayluke/spotube#2]
Hey!

I love spotube and have been using it for a while and I really shouldn't expect much for asking but here's my problem:
When I launch chrome for the first time and try to launch Spotube for the first time it suddenly opens and closes a tab which makes me have to reopen the extension when I'm back on youtube. I don't know why this is (says: authorizing) and it only happens when I launch chrome for the first time. It can get quite annoying but if you don't have time it's fine, it's just a quality of life thing...

Sry for bothering you and have a nice day!

**Comment by dayluke** [comment]
Hi Tristan,

Thank you for your kind words, and support for this project. I'm always open to suggestions!
Having just started development, again (sorry for the 4 month wait!), I have managed to update the Chrome Manifest version that this project uses. However, to my disappointment, I am still unable to change the current focus to a specific tab. Therefore, it displeases me to say that unfortunately, I won't be able to implement your suggestion.

Once again, I appreciate your support and goodwill, and I'd be more than happy to look into any other features you may want me to implement.

Luke.
